services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  kafka:
    image: bitnami/kafka:3.5
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server=localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      zookeeper:
        condition: service_healthy

  config-server:
    platform: linux/amd64
    build: ./config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/application/default"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      kafka:
        condition: service_healthy

  api-gateway:
    platform: linux/amd64
    build: ./api-gateway
    ports:
      - 8080:8080
    depends_on:
      config-server:
        condition: service_healthy

  game-service:
    platform: linux/amd64
    build: ./game-service
    depends_on:
      config-server:
        condition: service_healthy

  player-service:
    platform: linux/amd64
    build: ./player-service
    depends_on:
      config-server:
        condition: service_healthy

  leaderboard-service:
    platform: linux/amd64
    build: ./leaderboard-service
    depends_on:
      config-server:
        condition: service_healthy

  statistics-service:
    platform: linux/amd64
    build: ./statistics-service
    depends_on:
      config-server:
        condition: service_healthy
