server:
  port: 8081
  forward-headers-strategy: framework

spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  player-service:
    url: player-service:8082

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
  override-with-gateway-url: true