server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:statisticsdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: stats-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"